import styles from './css/home.css'
import Banner from './components/banner'
import { listAccomodations } from '@/public/data/accomodations'
import Thumb from './components/thumb'

export const metadata = {
    title: 'Kasa - Accueil',
    description: 'Generated by create next app',
}

export default function page() {

    const urlImage = '/images/landscape_home.png'
    return (
        <main id={styles.home}>
            <Banner image={urlImage} />

            <section className={styles.thumbs_container}>
                {listAccomodations && listAccomodations.map((accomodations) => (
                    <Thumb
                        key={accomodations.id}
                        id={accomodations.id}
                        title={accomodations.title}
                        cover={accomodations.cover}
                    />
                ))}
            </section>
        </main>
    )
}